FROM --platform=linux/arm/v6 navikey/raspbian-bullseye:latest

RUN apt-get -y update && \
    DEBIAN_FRONTEND="noninteractive" TZ="Europe/London" apt-get -y install autoconf automake bison bzip2 cmake doxygen flex g++ gcc \
    git gzip libarchive-dev libcurl4 libcurl4-openssl-dev libelf-dev libgpgme-dev libncurses5-dev libreadline-dev libssl-dev \
    libtool-bin libusb-dev m4 make patch pkg-config python3 python3-venv subversion tar tcl texinfo unzip wget xz-utils \
    sudo fakeroot libarchive-tools curl libgmp3-dev libmpfr-dev libmpc-dev python3-pip  && echo "dash dash/sh boolean false"| debconf-set-selections && sudo dpkg-reconfigure --frontend=noninteractive dash

# https://github.com/moby/moby/issues/4064
RUN ln -s /proc/mounts /etc/mtab

ENV PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
ENV PATH="/usr/local/opt/libtool/libexec/gnubin:$PATH" 
ENV PKG_CONFIG_PATH="/usr/local/opt/libarchive/lib/pkgconfig:/usr/local/opt/openssl@3/lib/pkgconfig" 
ENV PSPDEV=/usr/local/pspdev/
ENV PATH=$PATH:$PSPDEV/bin
COPY . /pspdev
WORKDIR /pspdev
RUN ./build-all.sh

