name: CI-Foreign-Arch

on:
  push:
    branches:
      - master
    tags:
      - v*
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        docker_platform:
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
          - linux/riscv64
        include:
          - docker_platform: linux/arm/v6
            human_platform: armv6
            base_image: "alpine:3.16"
          - docker_platform: linux/arm/v7
            human_platform: armv7
            base_image: "alpine:3.16"
          - docker_platform: linux/arm64
            human_platform: arm64
            base_image: "alpine:3.16"
          - docker_platform: linux/riscv64
            human_platform: riscv64gc
            base_image: "riscv64/alpine:edge"

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "./cross/Dockerfile.cross-alpine"
          platforms: ${{ matrix.docker_platform }}
          build-args: DOCKER_CROSS_BASE=${{ matrix.base_image }}
          outputs: type=tar,dest=/tmp/pspdev-${{ matrix.human_platform }}.tar

      - run: gzip /tmp/pspdev-${{ matrix.human_platform }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pspdev-${{ matrix.human_platform }}.tar.gz
          path: /tmp/pspdev-${{ matrix.human_platform }}.tar.gz
